name: flutter_bunny
description: A CLI Tools Command-Line application for generating flutter project.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  ansicolor: ^2.0.2
  args: ^2.5.0
  cli_completion: ^0.5.0
  collection: ^1.18.0
  equatable: ^2.0.5
  glob: ^2.1.2
  lcov_parser: ^0.1.2
  mason: ^0.1.0-dev.53
  mason_logger: ^0.2.15
  meta: ^1.14.0
  mockito: ^5.4.4
  package_config: ^2.1.0
  pub_updater: ^0.4.0
  sprintf: ^7.0.0
  universal_io: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.9
  build_verify: ^3.1.0
  build_version: ^2.1.1
  lints: ^3.0.0
  mocktail: ^1.0.3
  test: ^1.24.0
